### ISSUE TITLE
언제 업데이트되나요

### ISSUE THREAD

**Issue by silverstar0727** [ohjoonhee/lightning-codebase#1]
버젼2 언제나와요 nlp 최적화도 해주세요

**Comment by ohjoonhee** [comment]
다소 복잡한것 같아 인터페이스 전면 개편을 고려하고 있습니다. 
Huggingface Integration 방안도 모색중입니다. 

내실 있는 업데이트 조속히 이루어질 수 있도록 최선을 다하겠습니다. 

끝.

**Comment by silverstar0727** [comment]
노고에 감사드립니다.

필승.
